baseURL = "https://www.zerotoasiccourse.com/"
languageCode = "en-us"
title = "Zero to ASIC Course"
theme = "ananke"
Paginate = 9

[params]
  site_logo = "/zero-to-asic-logo-white-transp.png"
  favicon = "/zero-to-asic-logo-transp.png"
  stripe_test = "false"
  description = "Learn how to make your own chips!"
  title = "Zero to ASIC Course"
  images = ["zero-to-asic-logo-white-bg.png"]
  captcha_key = "6LeFKlcdAAAAAA6sEbdU78sUuy0lPezU-0H0JueA"
  editURL = "https://github.com/mattvenn/zero-to-asic-www/edit/main/content/"

[menu]

[[menu.main]]
identifier = "Terminology"
name = "Terminology"
url = "/terminology"
weight = 40

[[menu.main]]
identifier = "Articles"
name = "Articles"
url = "/post"
weight = 20

[[menu.main]]
identifier = "Interviews"
name = "Interviews"
url = "/interviews"
weight = 30

[[menu.main]]
identifier = "Matt Venn"
name = "About Matt Venn"
url = "/matt_venn"
weight = 25

[[menu.main]]
identifier = "Buy a ticket"
name = "Buy a ticket"
url = "/#tickets"
weight = 60
[menu.main.params]
      class = "button"

[[menu.main]]
identifier = "Newsletter"
name = "Newsletter"
url = "/newsletter"
weight = 30

[[menu.main]]
identifier = "Resources"
name = "Resources"
url = "/resources"
weight = 30

[[menu.main]]
identifier = "Videos"
name = "Videos"
url = "https://youtube.com/zerotoasic"
weight = 50
